### ISSUE TITLE
Possível pivot de ideia 

### ISSUE THREAD

**Issue by gabrielziegler3** [deeplearningunb/pneumonia-diagnose#11]
O repositório atual estudado está muito desatualizado e abandonado pelo autor, então estou cogitando mudar a ideia do projeto para produzir um notebook `demo.ipynb` utilizando TF 2.0 para demonstrar a implementação de [SRGAN](https://github.com/tensorlayer/srgan).

**Comment by gabrielziegler3** [comment]
Vamos trabalhar com o dataset [Chest X-Ray Images (Pneumonia)](https://www.kaggle.com/paultimothymooney/chest-xray-pneumonia) porque nos da mais chance de explorar mais tecnicas. Vamos mudar o repositorio todo para esse projeto agora

**Comment by ErickGiffoni** [comment]
perfeito
