### ISSUE TITLE
Configurar CI

### ISSUE THREAD

**Issue by gabrielziegler3** [deeplearningunb/pneumonia-diagnose#5]
- [x] Configurar CI para rodar build sempre que pushar um commit a uma branch

**Comment by frclba** [comment]
- [ ] pedir autorização para adicionar travis CI na organização
ou
- [x] pedir autorização para adicionar github actions na organização

**Comment by frclba** [comment]
https://github.com/features/actions/signup

**Comment by frclba** [comment]
@diegodorgam
